import fs from 'fs';
import path from 'path';
import url from 'url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const candidates = [
    'node_modules/circomlibjs/src/poseidon/poseidon_constants.json',
    'node_modules/circomlibjs/src/poseidon_constants.json',
    'node_modules/circomlibjs/poseidon_constants.json',
];

function toHex(v) {
    if (typeof v === 'string') {
        if (v.startsWith('0x') || v.startsWith('0X')) return '0x' + v.slice(2).toLowerCase();
        return '0x' + BigInt(v).toString(16);
    }

    if (typeof v === 'number') {
        return '0x' + BigInt(v).toString(16);
    }

    if (typeof v === 'bigint') {
        return '0x' + v.toString(16);
    }

    throw new Error('unsupported constant type: ' + typeof v);
}
const chunk = (arr, size) => Array.from({length: Math.ceil(arr.length/size)}, (_,i)=>arr.slice(i*size,(i+1)*size));

let constantsPath = null, constants = null;
for (const rel of candidates) {
    const p = path.join(root, rel);

    if (fs.existsSync(p)) {
        constants = JSON.parse(fs.readFileSync(p, 'utf8'));
        constantsPath = p;

        break;
    }
}

if (!constants || !constants.C || !constants.M) {
    console.error("Cannot find {C, M} in poseidon_constants.json");
    process.exit(1);
}

let idx = -1;
if (Array.isArray(constants.M)) {
    for (let i = 0; i < constants.M.length; i++) {
        const mat = constants.M[i];

        if (Array.isArray(mat) && mat.length === 3 && Array.isArray(mat[0]) && mat[0].length === 3) {
            idx = i;
            break;
        }
    }
} else if (typeof constants.M === 'object') {
    if (constants.M['3']) idx = '3';
    else if (constants.M[3]) idx = 3;
}

if (idx === -1) {
    console.error("Could not find 3x3 MDS in M at", constantsPath);
    process.exit(1);
}

const mds = constants.M[idx];
let arkEntry = constants.C[idx];

let arkRows;
if (Array.isArray(arkEntry) && arkEntry.length && Array.isArray(arkEntry[0])) {
    arkRows = arkEntry;
} else if (Array.isArray(arkEntry)) {
    arkRows = chunk(arkEntry, 3);
} else {
    console.error("Unexpected ark format for C[idx]");
    process.exit(1);
}

const rounds = arkRows.length;
const full_rounds = 8;
const partial_rounds = rounds - full_rounds;

const lines = [];
lines.push('// === AUTO-GENERATED by dump_poseidon_t3.js ===');
lines.push('// source: ' + constantsPath);

lines.push('(');
lines.push(`  ${full_rounds},`);
lines.push(`  ${partial_rounds},`);
lines.push('  vec![');
for (const row of mds) {
    lines.push(`    vec![ ${row.map(x => `fr("${toHex(x)}")`).join(', ')} ],`);
}
lines.push('  ],');
lines.push('  vec![');
for (const row of arkRows) {
    lines.push(`    vec![ ${row.map(x => `fr("${toHex(x)}")`).join(', ')} ],`);
}
lines.push('  ]');
lines.push(')');

const outPath = path.join(root, 'poseidon_t3_rust_consts.rs');

fs.writeFileSync(outPath, lines.join('\n'));

console.log('Generated:', outPath);
console.log('   src   =', constantsPath);
console.log('   mds   =', mds.length, 'x', mds[0].length);
console.log('   rounds=', rounds, '(rf=', full_rounds, ', rp=', partial_rounds, ')');