import fs from 'fs';
import path from 'path';
import url from 'url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const candidates = [
    'node_modules/circomlibjs/src/poseidon_constants.json',
    'node_modules/circomlibjs/src/poseidon/poseidon_constants.json',
    'node_modules/circomlibjs/poseidon_constants.json',
];

function toHex(v) {
    if (typeof v === 'string') {
        if (v.startsWith('0x') || v.startsWith('0X')) return '0x' + v.slice(2).toLowerCase();
        return '0x' + BigInt(v).toString(16);
    }

    if (typeof v === 'number') {
        return '0x' + BigInt(v).toString(16);
    }

    if (typeof v === 'bigint') {
        return '0x' + v.toString(16);
    }

    throw new Error('unsupported constant type: ' + typeof v);
}

function chunk(arr, size) {
    const out = [];
    for (let i = 0; i < arr.length; i += size) {
        out.push(arr.slice(i, i + size));
    }
    return out;
}

let constantsPath = null, constants = null;
for (const rel of candidates) {
    const p = path.join(root, rel);

    if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, 'utf8');
        constants = JSON.parse(raw);
        constantsPath = p;

        break;
    }
}

if (!constants || !constants.C || !constants.M) {
    console.error("Cannot find {C, M} in poseidon_constants.json");
    process.exit(1);
}

let idx = -1;
if (Array.isArray(constants.M)) {
    for (let i = 0; i < constants.M.length; i++) {
        const mat = constants.M[i];

        if (Array.isArray(mat) && mat.length === 3 && Array.isArray(mat[0]) && mat[0].length === 3) {
            idx = i;
            break;
        }
    }
}

if (idx === -1 && typeof constants.M === 'object') {
    if (constants.M['3']) idx = '3';
    if (constants.M[3]) idx = 3;
}

if (idx === -1) {
    console.error("Could not find 3x3 MDS in M array/object at", constantsPath);
    process.exit(1);
}

const mds = constants.M[idx];
let arkEntry = constants.C[idx];

let arkRows;
if (Array.isArray(arkEntry) && arkEntry.length && Array.isArray(arkEntry[0])) {
    arkRows = arkEntry;
} else if (Array.isArray(arkEntry)) {
    const t = 3;
    arkRows = chunk(arkEntry, t);
} else {
    console.error("Unexpected ark format for C[idx]");
    process.exit(1);
}

const lines = [];
lines.push('// === AUTO-GENERATED by dump_poseidon_t3.js ===');
lines.push('let mds: Vec<Vec<Fr>> = vec![');
for (const row of mds) {
    const rowRust = row.map(x => `fr("${toHex(x)}")`).join(', ');
    lines.push(`  vec![ ${rowRust} ],`);
}
lines.push('];\n');

lines.push('let ark: Vec<Vec<Fr>> = vec![');
for (const row of arkRows) {
    const rowRust = row.map(x => `fr("${toHex(x)}")`).join(', ');
    lines.push(`  vec![ ${rowRust} ],`);
}
lines.push('];\n');

const outPath = path.join(root, 'poseidon_t3_rust_consts.rs');
fs.writeFileSync(outPath, lines.join('\n'));
console.log('Generated:', outPath);
console.log('   mds  =', mds.length, 'x', mds[0].length);
console.log('   ark  =', arkRows.length,  'x', arkRows[0].length);